#! /bin/bash
# This script implements an archiving back up capability that I have
#   been thinking about for quite a while.  I have been using a
#   similar script except that it had a specific itemized list of
#   folders to be archived and a fixed volume destination folder.
#
# This version provides a start to an equivalent capability that
#   accepts the destination folder as an argument, and uses a config
#   file to specify the list of folders to be backed up segregated
#   by type.
#
# Copyright 2019 by George Ganoe
#
# This bash script is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2 of the
#   License, or (at your option) any later version.
#
# This bash script is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA

origFldr=$PWD
userNm=${HOME##*/}
bdate=$(date +%Y%m%d)

remPrompt()
{
    echo
    echo "It is best if no processes that change files are running"
    echo "  during the back up operation.  Also, it is a good idea"
    echo "  to clear the cache for browsers and other applications"
    echo "  that may write temporary data to folders that are to"
    echo "  be backed up."
    echo "  "
}

usage ()
{
    echo "backup-archive must be invoked with a parameter naming the"
    echo "  destination folder, (i. e. -"
    echo "    cmd prompt:~${PWD#$HOME}$ backup-archive dest-folder"
    echo "    where dest-folder is ideally the non-relative folder"
    echo "    name of the destination for the back up)"
    echo
    echo "Also a file named backup-archive.conf must be placed in the"
    echo "  $HOME/.config/backup folder containing the list of folders"
    echo "  that are to be backed up.  The config file has two"
    echo "  categories of folders.  They are [back up only] and"
    echo "  [maintain archive].  It can also have a [base] (to be"
    echo "  added later) section which can specify the base folder"
    echo "  that contains the list of the folders below to be backed"
    echo "  up.  The [base] section must come first if it exists."
    echo "  If it doesn't exist then the default is the users HOME"
    echo " folder."
    echo
    echo "The [back up only] folders will typically contain a local"
    echo "  repository that automatically maintains an archive of the"
    echo "  contents of the folder thus making an additional archive"
    echo "  redundant.  However, it may also be used for any folder"
    echo "  the user does not want to keep archived."
    echo
    echo "The [maintain archive] folders list will be backed up and"
    echo "  automatically store the old version of any changed or"
    echo "  deleted files.  Old versions will be stored in folder"
    echo "  ${userNm}-bu-${bdate} of the destination volume"
    echo "  which will be created if needed."
    remPrompt
}

if [ -n "$1" ] && [ -d "$1" ]; then
    destFldr=$1
else
    usage
    exit 1
fi

if [ ! -w "$destFldr" ]; then
    echo "Error: The folder $destFldr is not usable for back up."
    echo
    usage
    exit 1
elif [ -d "$destFldr/$userNm" ] && [ -w "$destFldr/$userNm" ]; then
    echo "The destination is good."
elif [ -d "$destFldr/$userNm" ]; then
    echo "Error: The folder $destFldr/$userNm is not writable."
    echo
    usage
    exit 1
else
    mkdir $destFldr/$userNm
    echo "The user back up folder $destFldr/$userNm was created."
fi

configFile="$HOME/.config/backup/backup-archive.conf"
baseFldr=$HOME
archiveOld=null
declare -a buoFldrs
declare -i buoIndNxt=0
declare -a maFldrs
declare -i maIndNxt=0

echo "Parameter origFldr = $origFldr"
echo "Parameter userNm = $userNm"
echo "Parameter bdate = $bdate"
echo "Parameter destFldr = $destFldr"
echo "Parameter configFile = $configFile"
echo "Parameter baseFldr = $baseFldr"
echo "Parameter archiveOld = $archiveOld"

remPrompt
echo "When you are ready, you may continue to perform the back up,"
echo "  do a dry run which will go through the motions without"
echo "  changing the destination folder, or quit the script and"
echo "  return to the terminal prompt."
echo
echo -n "Do you wish to continue [n=quit, y=do backup, d=dry run]? "
read resp1 resp2

# This variable determines whether the rsync commands below will
#   be active or be a dry run.  For a dry run use "in", and for an
#   active run use "iv".  See rsync the man page for the meanings
#   of these options.
ropt1=in

echo "resp1 is [$resp1], and resp2 is [$resp2]."

if [ $resp1 == "y" ] || [ $resp1 == "yes" ]; then
    ropt1=iv
    echo
elif [ $resp1 == "d" ] || [ $resp1 == "dry" ]; then
    ropt1=in
    echo
else
    echo "Exiting the backup-archive script as requested"
    exit 1
fi

cd $baseFldr
shopt -s lastpipe

if [ -r $configFile ]; then
    cat $configFile | while read resp1; do
        if [ -n "$resp1" ]; then
            if [ "${resp1:0:1}" == "[" ]; then
                if [ "${resp1:1:12}" == "back up only" ]; then
                    archiveOld=false
                elif [ "${resp1:1:16}" == "maintain archive" ]; then
                    archiveOld=true
                else
                    echo "Error: Unexpected section name in the config file"
                    exit 1
                fi
            else
                if [ -r $resp1 ]; then
                    if [ $archiveOld == true ]; then
                        maFldrs[$((maIndNxt++))]=$resp1
                    else
                        buoFldrs[$((buoIndNxt++))]=$resp1
                    fi
                fi
            fi
        fi
        echo "archiveOld=$archiveOld, maIndNxt=$maIndNxt, buoIndNxt=$buoIndNxt, resp1=[$resp1]"
    done
    echo "Final archiveOld=$archiveOld, maIndNxt=$maIndNxt, buoIndNxt=$buoIndNxt, resp1=[$resp1]"
fi

declare -i ind

cd $destFldr
echo
echo "Changed to the destFldr, $destFldr"

# Error found when a path ending with a file name instead of a folder
#   name is specified for backup
# A work around for now is to require that only backup folders be specified
#   as source objects.  For the case which caused this error to be found,
#   the backup-archive.conf file is now allocated in its own folder so when
#   a new archive partition is used, it will be properly stored.

echo "These are the $buoIndNxt [back up only] folders"
for (( ind=0 ; buoIndNxt-ind ; ind++ )) ; do
    finalFldr=${buoFldrs[$ind]##*/}
    if [ $finalFldr != ${buoFldrs[$ind]} ]; then
        leadFldrs=${buoFldrs[$ind]%/*}
        if [ -r $baseFldr/$leadFldrs/$finalFldr ]; then
            echo "Running rsync -$ropt1 -aH --delete $baseFldr/$leadFldrs/$finalFldr $userNm/$leadFldrs"
            rsync -$ropt1 -aH --delete $baseFldr/$leadFldrs/$finalFldr $userNm/$leadFldrs
        else
            echo "Requested file $baseFldr/$leadFldrs/$finalFldr is not readable, skipping."
        fi
    else
        if [ -r $baseFldr/$finalFldr ]; then
            echo "Running rsync -$ropt1 -aH --delete $baseFldr/$finalFldr $userNm"
            rsync -$ropt1 -aH --delete $baseFldr/$finalFldr $userNm
        else
            echo "Requested file $baseFldr/$finalFldr is not readable, skipping."
        fi
    fi
done

echo
echo "These are the $maIndNxt [maintain archive] folders"
for (( ind=0 ; maIndNxt-ind ; ind++ )) ; do
    finalFldr=${maFldrs[$ind]##*/}
    if [ $finalFldr != ${maFldrs[$ind]} ]; then
        leadFldrs=${maFldrs[$ind]%/*}
        if [ -r $baseFldr/$leadFldrs/$finalFldr ]; then
            echo "Running rsync -$ropt1 -aH --backup --backup-dir=$destFldr/$userNm-bu-$bdate/$leadFldrs --delete $baseFldr/$leadFldrs/$finalFldr $userNm/$leadFldrs"
            rsync -$ropt1 -aH --backup --backup-dir=$destFldr/$userNm-bu-$bdate/$leadFldrs --delete $baseFldr/$leadFldrs/$finalFldr $userNm/$leadFldrs
        else
            echo "Requested file $baseFldr/$leadFldrs/$finalFldr is not readable, skipping."
        fi
    else
        if [ -r $baseFldr/$finalFldr ]; then
            echo "Running rsync -$ropt1 -aH --backup --backup-dir=$destFldr/$userNm-bu-$bdate --delete $baseFldr/$finalFldr $userNm"
            rsync -$ropt1 -aH --backup --backup-dir=$destFldr/$userNm-bu-$bdate --delete $baseFldr/$finalFldr $userNm
        else
            echo "Requested file $baseFldr/$finalFldr is not readable, skipping."
        fi
    fi
done

cd $origFldr

